Embedding Audio to Nodes
adityamukho/hivemind pull request #21
Opened 2021-12-05 04:14 UTC by candideu

Hello! I made a feature request a few days ago about embedding media - https://github.com/adityamukho/hivemind/issues/20. I decided to revisit the idea and see if I could contribute.

For now, I think I was able to figure out embedding audio from an external URL ([such as this](https://www.kozco.com/tech/piano2-CoolEdit.mp3)). Unfortunately, I wasn't able to test this out my self and build the app on my own. Please let me know if this works!

2021-12-07 07:09 UTC, adityamukho requested changes

2021-12-07 07:09 UTC, adityamukho commented on components/mindmap/EventDetail.js
> +              rows.appendChild(content)
```suggestion
              const audio = document.createElement('div')
              audio.classNames = ['row']
              audio.innerHTML = `<b>Audio:</b> ${d.audio}`
              rows.appendChild(audio)
```

2021-12-07 07:11 UTC, adityamukho commented
Please change base branch to `development`. Also, have suggested a few changes.

2021-12-07 10:10 UTC, adityamukho commented on components/mindmap/menu-items/view.js
> +                <source src="{data.audio}">
```suggestion
                <source src="{data.audio}"/>
```

2021-12-07 10:11 UTC, adityamukho commented on components/mindmap/menu-items/view.js
> +                <source src="{data.audio}">
Required to fix failed deployment: https://github.com/adityamukho/hivemind/pull/21#issuecomment-987766811

2021-12-07 15:58 UTC, candideu commented
Okay, I've implemented the changes and rebased. See this new PR: https://github.com/adityamukho/hivemind/pull/22

2021-12-08 03:14 UTC, adityamukho commented on components/mindmap/menu-items/edit.js
> +                maxLength="2,048"
```suggestion
                maxLength="2048"
```

The numeric value with a comma gets truncated to 2 when parsed.

2021-12-08 03:24 UTC, adityamukho commented
Follow-up at #22

2021-12-08 03:24 UTC, closed without merging